// <auto-generated />
namespace FRManager.DataContext.DyanamicData
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class nadeera : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nadeera));
        
        string IMigrationMetadata.Id
        {
            get { return "201505161208415_nadeera"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
