// <auto-generated />
namespace FRManager.DataContext.DBMain
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class message5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(message5));
        
        string IMigrationMetadata.Id
        {
            get { return "201505190716427_message 5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
